# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: YangYangBot Run

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  schedule:
    - cron:  '10 0/6 * * *'
#   status:
#     branches: [ master ]

jobs:
  job1:

    runs-on: windows-latest
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        node-version: [12.x]
    env: # Or as an environment variable
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
#    - uses: actions/upload-artifact@v2
#      if: ${{true}}
#      with:
#        name: songdata
#        path: dbdata/
#    - uses: actions/download-artifact@v2
#      with:
#        name: songdata
#        path: dbdata/
    - run: node index.js
      if: ${{true}}
#    - uses: actions/upload-artifact@v2
#      if: ${{true}}
#      with:
#        name: songdata
#        path: dbdata/

